apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::621486623993:role/eksctl-simple-cluster-nodegroup-st-NodeInstanceRole-qpYoTUgo6Zhq
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::621486623993:user/github-ci
      username: github-ci
      groups:
        - system:masters