name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::621486623993:role/github-actions-ecr-role
          aws-region: eu-north-1
      - name: Load secrets and save to app.env
        run: |
         aws secretsmanager get-secret-value --secret-id simple_bank \
           --query SecretString --output text \
         | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Debug list files
        run: |
          echo "ℹ️ Поточна директорія:"
          pwd
          echo "📁 Вміст:"
          ls -la
          echo "📄 app.env:"
          cat app.env

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg APP_ENV_FILE=app.env -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG